"""Build single-file distributions of the SELDI CMS dashboard.

Outputs (dist/):
  seldi-dashboard-wordpress.html
      A self-contained FRAGMENT (style + one script per source file).
      Paste it into a WordPress "Custom HTML" block — done.
  seldi-dashboard-standalone.html
      A full, self-contained HTML document (Chart.js bundled instead of
      CDN). Upload via FTP / file manager, or open locally.

Everything is inlined: CSS, data, Chart.js and the app code, so the result
has zero external requests. Re-run this script after every dashboard change
and re-paste / re-upload the output.

Usage:
    python build_singlefile.py
"""
import re
import pathlib
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent
DIST = ROOT / "dist"
VENDOR = ROOT / "assets" / "vendor"
CHART_URL = "https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"
CHART_CACHE = VENDOR / "chart.umd.min.js"


def read(rel):
    return (ROOT / rel).read_text(encoding="utf-8")


def js_safe(text):
    """Keep '</script>' inside JS strings from closing our tag early."""
    return text.replace("</script", "<\\/script")


def chart_js():
    """Bundle Chart.js from the local cache, downloading it once if needed."""
    if CHART_CACHE.exists():
        return CHART_CACHE.read_text(encoding="utf-8")
    print(f"downloading Chart.js -> {CHART_CACHE}")
    req = urllib.request.Request(CHART_URL, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        code = resp.read().decode("utf-8")
    if len(code) < 100_000:
        raise RuntimeError(f"suspiciously small Chart.js download ({len(code)} B)")
    VENDOR.mkdir(parents=True, exist_ok=True)
    CHART_CACHE.write_text(code, encoding="utf-8")
    return code


def build():
    css = read("assets/css/style.css")
    data = read("assets/js/data.js")
    dash = read("assets/js/dashboard.js")
    chart = chart_js()

    assert "</style" not in css.lower(), "CSS contains a </style sequence"
    for name, js in (("chart", chart), ("data", data), ("dashboard", dash)):
        assert js.strip(), f"{name}.js is empty"

    DIST.mkdir(exist_ok=True)

    # ---------- WordPress fragment ----------
    fragment = (
        "<!-- SELDI CMS 2025 Dashboard — self-contained.\n"
        "     WordPress: add a \"Custom HTML\" block on the page and paste\n"
        "     this entire file into it, then Update. Rebuild after dashboard\n"
        "     changes with:  python build_singlefile.py -->\n"
        "<style>\n" + css + "</style>\n"
        "<script>\n/* Chart.js 4.4.7 (MIT) — bundled, no external requests */\n"
        + js_safe(chart) + "\n</script>\n"
        "<script>\n/* SELDI CMS data (generated by extract_data.py) */\n"
        + js_safe(data) + "\n</script>\n"
        "<script>\n/* dashboard app */\n"
        + js_safe(dash) + "\n</script>"
    )
    wp_file = DIST / "seldi-dashboard-wordpress.html"
    wp_file.write_text(fragment, encoding="utf-8")

    # ---------- standalone document (from index.html, links inlined) ----------
    html = read("index.html")

    def css_sub(m):
        rel = m.group(1)
        return "<style>\n" + read(rel) + "</style>"

    def js_sub(m):
        src = m.group(1)
        if src.startswith(("http://", "https://")):
            code = chart if src == CHART_URL else (
                urllib.request.urlopen(src, timeout=60).read().decode("utf-8"))
        else:
            code = read(src)
        return "<script>\n" + js_safe(code) + "\n</script>"

    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', css_sub, html)
    html = re.sub(r'<script src="([^"]+)"></script>', js_sub, html)
    assert not re.search(r'(?:src|href)="(?:assets/|https?://)', html), \
        "standalone build still references external assets"
    st_file = DIST / "seldi-dashboard-standalone.html"
    st_file.write_text(html, encoding="utf-8")

    for f in (wp_file, st_file):
        print(f"wrote {f.relative_to(ROOT)}  ({f.stat().st_size // 1024} KB)")
    print("\nWordPress: paste the content of "
          "dist/seldi-dashboard-wordpress.html into a Custom HTML block.")
    print("FTP/static: upload dist/seldi-dashboard-standalone.html "
          "(e.g. as seldi.net/dashboard/index.html).")


if __name__ == "__main__":
    build()
